
from typing import OrderedDict


faces = OrderedDict([("5_o_Clock_Shadow", -1),
                     ("Arched_Eyebrows", -1),
                     ("Attractive", -1),
                     ("Bags_Under_Eyes", -1),
                     ("Bald", -1),
                     ("Bangs", -1),
                     ("Big_Lips", -1),
                     ("Big_Nose", -1),
                     ("Black_Hair", -1),
                     ("Blond_Hair", -1),
                     ("Blurry", -1),
                     ("Brown_Hair", -1),
                     ("Bushy_Eyebrows", -1),
                     ("Chubby", -1),
                     ("Double_Chin", -1),
                     ("Eyeglasses", -1),
                     ("Goatee", -1),
                     ("Gray_Hair", -1),
                     ("Heavy_Makeup", -1),
                     ("High_Cheekbones", -1),
                     ("Male", -1),
                     ("Mouth_Slightly_Open", -1),
                     ("Mustache", -1),
                     ("Narrow_Eyes", -1),
                     ("No_Beard", -1),
                     ("Oval_Face", -1),
                     ("Pale_Skin", -1),
                     ("Pointy_Nose", -1),
                     ("Receding_Hairline", -1),
                     ("Rosy_Cheeks", -1),
                     ("Sideburns", -1),
                     ("Smiling", -1),
                     ("Straight_Hair", -1),
                     ("Wavy_Hair", -1),
                     ("Wearing_Earrings", -1),
                     ("Wearing_Hat", -1),
                     ("Wearing_Lipstick", -1),
                     ("Wearing_Necklace", -1),
                     ("Wearing_Necktie", -1),
                     ("Young", -1)])
emotions = OrderedDict([("agreeableness", -1),
                        ("anger", -1),
                        ("anticipation", -1),
                        ("arrogance", -1),
                        ("disagreeableness", -1),
                        ("disgust", -1),
                        ("fear", -1),
                        ("gratitude", -1),
                        ("happiness", -1),
                        ("humility", -1),
                        ("love", -1),
                        ("optimism", -1),
                        ("pessimism", -1),
                        ("regret", -1),
                        ("sadness", -1),
                        ("shame", -1),
                        ("shyness", -1),
                        ("surprise", -1),
                        ("trust", -1),
                        ("neutral", -1)])
